### PR TITLE
Make game more dangerous! :D

### PR DESCRIPTION
**Pull request by lionleaf**
Sets bullet damage to 7  (2 shots to kill)
Bullets fly at double speed.
Can only shoot 2 shots per second.

### CODE REVIEW

**Comment by sigvef** [comment]
I think this change makes the game less fun. It also more or less nullifies the knockback mechanic, since now bullets are so deadly and seldomly fired that they cannot be used for "crowd control", i.e. pushing enemies out of position, onto or off of capture points, and so on.

**Comment by lionleaf** [comment]
I think it makes the game feel more skill-based and more exciting. 

I'm guessing we need more play testing on this (in at least 2v2 or 3v3). @iver56 @Raane, input?

I really like 2 hits to kill and lower firing rate; makes each bullet really count.
The bullet speed I'm less sure of.

**Comment by iver56** [comment]
My 2 cents: Instead of hard-coding this, have a set of game modes that can be selected in the game. Perhaps having two buttons for game mode voting (in the game over overlay after each round) would be a good idea?

Edit: Check out the [fun run app](https://play.google.com/store/apps/details?id=no.dirtybit.funrun&hl=no). Before each round, there are two maps that players can vote for. One vote for each player. The map with the most votes is chosen. Or, if it is a tie, a random map is chosen.

**Comment by lionleaf** [comment]
I would prefer to do some play testing and finding something we're happy with as the default at least. Not sure multiple game modes for different weapons is worth implementing without doing some bigger changes (different maps etc), but then we're talking quite a lot of work.

How about some play testing during AbelLAN?

If we're going for weak bullets I think it would help with healing on capture points. At the moment it is nearly impossible to get a kill and not show up for the next fight severely weakened. 

With the deadly bullets I enjoyed that it was a lot more possible to actually win a 2v1 fight

**Comment by sigvef** [comment]
A healing mechanic would give a lot to the game I think.

**Comment by cristeahub** [comment]
this actually needs rebase

**Comment by Raane** [comment]
This pull request is thoroughly dead.

**Comment by sigvef** [comment]
R.I.P.

**Pull request closed without merging**
